//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rede.PN.AtendimentoDigital.SharePoint.WebParts.AtendimentoDigital.Atendimento {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class Atendimento {
        
        public static implicit operator global::System.Web.UI.TemplateControl(Atendimento target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Rede.PN.AtendimentoDigital.SharePoint.WebParts.AtendimentoDigital.Atendimento.Atendimento @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/sites/fechado/Style Library/pt-" +
                        "br/Redecard/Stylesheet/redeareafechada-3-0-facelift-atendimento.min.css\" />\r\n<li" +
                        "nk rel=\"stylesheet\" type=\"text/css\" href=\"/sites/fechado/Style Library/Atendimen" +
                        "toDigital/css/atendimento.css\" />\r\n\r\n<div class=\"loading-spiner-holder\" data-loa" +
                        "ding></div>\r\n<div id=\"portal-content\" class=\"portal-container-fluid\" ng-app=\"ate" +
                        "ndimento\" ng-controller=\"atendimento\" ng-cloak>\r\n    <div class=\"portal-containe" +
                        "r-fluid\">\r\n        <div class=\"portal-container\">\r\n            <div class=\"porta" +
                        "l-content\">\r\n                <div class=\"subtitle\">escolha um de nossos serviços" +
                        " e um assunto sobre qual é a sua dúvida</div>\r\n                <div class=\"filte" +
                        "rs-box filters-white\">\r\n                    <div class=\"col-3\">\r\n               " +
                        "         <div class=\"col\">\r\n                            <div>\r\n                 " +
                        "               <select ng-change=\" bolSetDefaultOption = true; LoadSubCategories" +
                        "();\" ng-model=\"intCategory\" id=\"category\" class=\"rede-select\">\r\n                " +
                        "                    <option value=\"-1\" disabled=\"disabled\" selected=\"selected\">c" +
                        "ategoria</option>\r\n                                    <option ng-repeat=\"cat in" +
                        " arrCategorias\" value=\"{{ cat.ID }}\" faqdroprepeatdone>{{ cat.Title }}</option>\r" +
                        "\n                                </select>\r\n                            </div>\r\n" +
                        "                        </div>\r\n                        <div class=\"col\">\r\n     " +
                        "                       <div>\r\n                                <select ng-model=\"" +
                        "intSubCategory\" id=\"subCategory\" class=\"rede-select\">\r\n                         " +
                        "           <option value=\"-1\" disabled=\"disabled\" selected=\"selected\">subcategor" +
                        "ia</option>\r\n                                    <option ng-repeat=\"sCat in arrS" +
                        "ubCategoriasReady\" value=\"{{ sCat.ExibeMenu ? sCat.Id : sCat.PerguntaId }}\" data" +
                        "-scat-id=\"{{ sCat.Id }}\" data-scat-exibir=\"{{ sCat.ExibeMenu }}\" data-perg-id=\"{" +
                        "{ sCat.PerguntaId }}\" faqdroprepeatdone>{{ sCat.Title }}</option>\r\n             " +
                        "                   </select>\r\n                            </div>\r\n              " +
                        "          </div>\r\n                        <div class=\"col\">\r\n                   " +
                        "         <div>\r\n                                <div class=\"btn-rede margin-top-" +
                        "5\">\r\n                                    <div class=\"btn-primary\">\r\n            " +
                        "                            <input type=\"button\" value=\"buscar\" ng-click=\"ShowAs" +
                        "kFoot($event, true)\" data-gtm-attr=\"buscarPerguntaResposta\">\r\n                  " +
                        "                  </div>\r\n                                </div>\r\n              " +
                        "              </div>\r\n                        </div>\r\n                    </div>" +
                        "\r\n                </div>\r\n                <div class=\"faq-geral\">\r\n             " +
                        "       <div class=\"subtitle\">{{ strCategoryReady }}</div>\r\n                    <" +
                        "div class=\"faq-content\">\r\n                        <ul class=\"faq-list\">\r\n       " +
                        "                     <li class=\"faq-item\" ng-repeat=\"ask in arrPerguntaRespostas" +
                        "\" data-perg-id=\"{{ ask.Id }}\" faqlistrepeatdone>\r\n                              " +
                        "  <p class=\"faq-list-title\">\r\n                                    <span class=\"f" +
                        "aq-title\" data-gtm-attr=\"{{ ask.DescricaoSubcategoria.CategoriaSubcategoria }}\" " +
                        "id=\"titulo-{{ ask.ID }}\">{{ ask.Title }}</span>\r\n                               " +
                        "     <a class=\"jade-text right faq-query\" href=\"javascript:void(0)\" ng-click=\"Sh" +
                        "owVideoContent($event)\" data-gtm-attr=\"exibirResposta\" data-gtm-id-pergunta=\"{{a" +
                        "sk.ID}}\" data-gtm-hash-video=\"{{ask.URLVideo}}\">exibir</a>\r\n                    " +
                        "            </p>\r\n                                <div class=\"faq-description\">\r" +
                        "\n                                    <div class=\"FAQ-Videos\" style=\"background-c" +
                        "olor: #E0E0E0;\">\r\n                                        <div class=\"faq-video-" +
                        "pad\">\r\n                                            <p ng-bind-html=\"RenderHtml(a" +
                        "sk.Resposta)\" class=\"faq-answer\"></p>\r\n                                        <" +
                        "/div>\r\n                                        <div ng-show=\"ask.URLVideo && bol" +
                        "GeralShowVideo == true\">\r\n                                            <a href=\"j" +
                        "avascript:void(0)\" onclick=\"OpenPlayer(event)\" data-perg-id=\"{{ ask.ID }}\" data-" +
                        "perg-hash-video=\"{{ ask.HashVideo }}\">\r\n                                        " +
                        "        <img ng-src=\"{{ ask.UrlImgVideo }}\" />\r\n                                " +
                        "            </a>\r\n                                            <div id=\"dialog-{{" +
                        "ask.ID}}\" class=\"modal-rede\"></div>\r\n                                        </d" +
                        "iv>\r\n                                    </div>\r\n                               " +
                        "     <hr class=\"faq-hr\" />\r\n                                    <div class=\"faq-" +
                        "answer-interaction\">\r\n                                        <div class=\"bottom" +
                        "-20 faq-answer-interaction-options\">\r\n                                          " +
                        "  <p class=\"bottom-20\">A resposta acima ajudou você a solucionar o seu problema?" +
                        "</p>\r\n                                            <span>\r\n                      " +
                        "                          <input type=\"radio\" name=\"rdnFaqUtil\" ng-click=\"Change" +
                        "RadioFaqDescriptionAsk($event)\" value=\"sim\" faqradio data-gtm-attr=\"avaliarRespo" +
                        "sta\" data-gtm-id-pergunta=\"{{ask.ID}}\" />\r\n                                     " +
                        "           <label class=\"right-15\">Sim</label>\r\n                                " +
                        "            </span>\r\n                                            <span>\r\n       " +
                        "                                         <input type=\"radio\" name=\"rdnFaqUtil\" n" +
                        "g-click=\"ChangeRadioFaqDescriptionAsk($event)\" value=\"nao\" faqradio data-gtm-att" +
                        "r=\"avaliarResposta\" data-gtm-id-pergunta=\"{{ask.ID}}\" />\r\n                      " +
                        "                          <label>Não</label>\r\n                                  " +
                        "          </span>\r\n                                        </div>\r\n             " +
                        "                           <div class=\"faq-answer-interaction-other-topic displa" +
                        "y-none\">\r\n                                            <p class=\"bottom-20\">Selec" +
                        "ione o item abaixo que mais se relaciona a sua dúvida ou problema?</p>\r\n        " +
                        "                                    <ol class=\"bottom-20 disc-orange-list faq-an" +
                        "swer-interaction-other-topic-list\">\r\n                                           " +
                        "     <div class=\"col-4\">\r\n                                                    <l" +
                        "i class=\"col\" ng-repeat=\"sCateg in GetSubCategoriesPerCategory(ask.CategoriaId)\"" +
                        ">\r\n                                                        <a href=\"javascript:v" +
                        "oid(0)\" data-cat-id=\"{{ ask.CategoriaId }}\" data-scat-id=\"{{ sCateg.Id }}\" data-" +
                        "scat-exibir=\"{{ sCateg.ExibeMenu }}\" data-perg-id=\"{{ sCateg.PerguntaId }}\" ng-c" +
                        "lick=\"RedirectCategory($event)\" class=\"list-title\" data-gtm-attr=\"vitrineRespost" +
                        "a\" data-gtm-id-pergunta=\"{{ask.ID}}\">{{ sCateg.Title }}</a></li>\r\n              " +
                        "                                  </div>\r\n                                      " +
                        "      </ol>\r\n                                            <div class=\"faq-answer-" +
                        "interaction-other-topic-fale-conosco\">\r\n                                        " +
                        "        <p>Caso não seja nenhum desses itens, você pode enviar uma mensagem atra" +
                        "vés do <a class=\"jade-text\" href=\"/sites/fechado/Paginas/AtendimentoDigital/Fale" +
                        "Conosco.aspx\" data-gtm-attr=\"faleConosResposta\" data-gtm-id-pergunta=\"{{ask.ID}}" +
                        "\">fale conosco.</a></p>\r\n                                            </div>\r\n   " +
                        "                                     </div>\r\n                                   " +
                        "     <div class=\"faq-thanks-message display-none\">\r\n                            " +
                        "                <p>Muito obrigado pela sua resposta. Ficamos felizes em ter ajud" +
                        "ado ;)</p>\r\n                                        </div>\r\n                    " +
                        "                </div>\r\n                                </div>\r\n                " +
                        "            </li>\r\n                        </ul>\r\n                        <p cla" +
                        "ss=\"faq-list-title-last\">\r\n                            <a class=\"jade-text right" +
                        "\" ng-click=\"ShowAllAsks($event)\" id=\"btnVerMais\" href=\"javascript:void(0)\">ver m" +
                        "ais</a>\r\n                        </p>\r\n                    </div>\r\n             " +
                        "   </div>\r\n                <!-- Carrossel de vídeos -->\r\n                <div ng" +
                        "-show=\"bolGeralShowVideo == true\">\r\n                    <div class=\"content-row\"" +
                        ">\r\n                        <div class=\"title\">Veja como é fácil utilizar</div>\r\n" +
                        "                        <div class=\"commom-text margin-bottom-sm\"></div>\r\n      " +
                        "                  <div class=\"video-carousel\">\r\n                            <div" +
                        " class=\"owl-carousel simple-carousel-rede\" carouselelement>\r\n                   " +
                        "             <div class=\"item\" ng-repeat=\"videoGroup in arrVideos\">\r\n           " +
                        "                         <span ng-repeat=\"video in videoGroup\">\r\n               " +
                        "                         <a class=\"video-thumb-rede\" href=\"javascript:void(0)\" o" +
                        "nclick=\"OpenPlayer(event)\" data-perg-id=\"carrossel-{{ video.videoId}}\" data-perg" +
                        "-hash-video=\"{{ video.videoId }}\" data-gtm-attr=\"videoCarrossel\" data-gtm-titulo" +
                        "-video=\"{{ video.titulo }}\">\r\n                                            <img c" +
                        "lass=\"owl-lazy\" ng-src=\"{{ video.thumbnail.url }}\" />\r\n                         " +
                        "                   <span class=\"bold video-title-rede\">{{video.titulo}}</span>\r\n" +
                        "                                        </a>\r\n                                  " +
                        "  </span>\r\n                                </div>\r\n                            <" +
                        "/div>\r\n                        </div>\r\n                    </div>\r\n             " +
                        "       <div ng-repeat=\"videoGroup in arrVideos\">\r\n                        <div n" +
                        "g-repeat=\"video in videoGroup\">\r\n                            <div id=\"dialog-car" +
                        "rossel-{{ video.videoId}}\" class=\"modal-rede\"></div>\r\n                        </" +
                        "div>\r\n                    </div>\r\n                </div>\r\n                <div c" +
                        "lass=\"faq-box\">\r\n                    <div class=\"subtitle\">mais informações</div" +
                        ">\r\n                    <ul>\r\n                        <div class=\"col-4\" ng-repea" +
                        "t=\"chunckedCateg in arrCategoriasChuncked\">\r\n                            <li cla" +
                        "ss=\"col\" data-cat-id=\"{{ categ.Id }}\" ng-repeat=\"categ in chunckedCateg\">\r\n     " +
                        "                           <div class=\"money-values\">\r\n                         " +
                        "           <div class=\"value-box\">\r\n                                        <div" +
                        " class=\"value\">\r\n                                            <div class=\"commom-" +
                        "text-bold\" id=\"categoria-{{categ.ID}}\">{{ categ.Title }}</div>\r\n                " +
                        "                        </div>\r\n                                        <div cla" +
                        "ss=\"value value-child\">\r\n                                            <div>\r\n    " +
                        "                                            <ul class=\"disc-orange-list\">\r\n     " +
                        "                                               <li ng-repeat=\"sCateg in GetSubCa" +
                        "tegoriesPerCategory(categ.Id)\">\r\n                                               " +
                        "         <a data-scat-id=\"{{ sCateg.Id }}\" data-scat-exibir=\"{{ sCateg.ExibeMenu" +
                        " }}\" data-perg-id=\"{{ sCateg.PerguntaId }}\" href=\"javascript:void(0)\" ng-click=\"" +
                        "ShowAskFoot($event, true)\" class=\"list-title\" data-gtm-categoria-vitrine-id=\"{{c" +
                        "ateg.ID}}\" data-gtm-attr=\"subcategoriaVitrine\">{{ sCateg.Title }}</a>\r\n         " +
                        "                                           </li>\r\n                              " +
                        "                  </ul>\r\n                                            </div>\r\n   " +
                        "                                     </div>\r\n                                   " +
                        " </div>\r\n                                </div>\r\n                            </l" +
                        "i>\r\n                        </div>\r\n                    </ul>\r\n                <" +
                        "/div>\r\n                <div class=\"faq-foot-contact\">\r\n                    <div " +
                        "class=\"subtitle\">fale com a gente</div>\r\n                    <div class=\"filters" +
                        "-box filters-white\">\r\n                        <div class=\"col-2\">\r\n             " +
                        "               <div class=\"col\">\r\n                                <div class=\"mo" +
                        "ney-values\">\r\n                                    <div class=\"value-box\">\r\n     " +
                        "                                   <div class=\"value faq-autoatendimento-line\">\r" +
                        "\n                                            <p class=\"faq-autoatendimento-icon " +
                        "mensagem\"></p>\r\n                                            <div class=\"commom-t" +
                        "ext-bold\">Envie uma mensagem</div>\r\n                                        </di" +
                        "v>\r\n                                        <div class=\"value value-icon\">\r\n    " +
                        "                                        <p>Conte para a gente qual é sua dúvida " +
                        "ou problema com o máximo de detalhes possível.</p>\r\n                            " +
                        "            </div>\r\n                                    </div>\r\n                " +
                        "                    <p class=\"jade-text right\">\r\n                               " +
                        "         <a href=\"/sites/fechado/Paginas/AtendimentoDigital/FaleConosco.aspx\" da" +
                        "ta-gtm-attr=\"faleConoscoQuadro\">enviar mensagem</a>\r\n                           " +
                        "         </p>\r\n                                </div>\r\n                         " +
                        "   </div>\r\n                            <div class=\"col\">\r\n                      " +
                        "          <div class=\"money-values\">\r\n                                    <div c" +
                        "lass=\"value-box\">\r\n                                        <div class=\"value faq" +
                        "-autoatendimento-line\">\r\n                                            <p class=\"f" +
                        "aq-autoatendimento-icon telefone\"></p>\r\n                                        " +
                        "    <div class=\"commom-text-bold\">Telefones de contato</div>\r\n                  " +
                        "                      </div>\r\n                                        <div class" +
                        "=\"value value-icon\">\r\n                                            <p>Entre em co" +
                        "ntato conosco pelos telefones de atendimento disponível para capitais e outras r" +
                        "egiões.</p>\r\n                                        </div>\r\n                   " +
                        "                 </div>\r\n                                    <p class=\"jade-text" +
                        " right\">\r\n                                        <a class=\"pointer\" onclick=\"ja" +
                        "vascript:OpenModal()\" data-gtm-attr=\"ver-telefones\">ver telefones</a>\r\n         " +
                        "                           </p>\r\n                                </div>\r\n       " +
                        "                     </div>\r\n                        </div>\r\n                   " +
                        " </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r" +
                        "\n</div>\r\n\r\n\r\n<div id=\"dialog-tel\" title=\"Atendimento\" class=\"modal-rede custom-t" +
                        "itle-modal\">\r\n    <hr class=\"modal-hr\" />\r\n    <div class=\"faq-foot-contact\">\r\n " +
                        "       <div class=\"col-2\">\r\n            <div class=\"col\">\r\n                <div " +
                        "class=\"money-values\">\r\n                    <div class=\"value-box\">\r\n            " +
                        "            <div class=\"value faq-autoatendimento-line\">\r\n                      " +
                        "      <p class=\"faq-autoatendimento-icon telefone\"></p>\r\n                       " +
                        "     <div class=\"commom-text-bold\">Telefones de contato</div>\r\n                 " +
                        "       </div>\r\n                        <div class=\"value value-icon\">\r\n         " +
                        "                   <p>\r\n                                Em caso de dúvidas, ligu" +
                        "e para:\r\n                                <br>\r\n                                <" +
                        "br>\r\n                                •  4001-4433 (capitais e regiões metropolit" +
                        "anas)\r\n                                <br>\r\n                                <br" +
                        ">\r\n                                •  0800 728 4433 (demais localidades)\r\n      " +
                        "                          <br>\r\n                                <br>\r\n          " +
                        "                      De segunda a sábado, das 8h às 22h.\r\n                     " +
                        "           <br>\r\n                                Domingos e feriados, das 9h às " +
                        "21h.\r\n                            </p>\r\n                        </div>\r\n        " +
                        "            </div>\r\n\r\n                </div>\r\n            </div>\r\n            <d" +
                        "iv class=\"col\">\r\n                <div class=\"money-values\">\r\n                   " +
                        " <div class=\"value-box\">\r\n                        <div class=\"value faq-autoaten" +
                        "dimento-line\">\r\n                            <p class=\"faq-autoatendimento-icon o" +
                        "uvidoria\"></p>\r\n                            <div class=\"commom-text-bold\">Ouvido" +
                        "ria</div>\r\n                        </div>\r\n                        <div class=\"v" +
                        "alue value-icon\">\r\n                            <p>\r\n                            " +
                        "    Caso você tenha entrado em contato com a Rede e não ficou satisfeito com o a" +
                        "tendimento, ligue para nossa Ouvidoria.\r\n                            <br>\r\n     " +
                        "                           <br>\r\n                                •  0800 720 006" +
                        "0 (todas as localidades)\r\n                            </p>\r\n                    " +
                        "    </div>\r\n                    </div>\r\n                </div>\r\n            </di" +
                        "v>\r\n        </div>\r\n    </div>\r\n    <hr class=\"modal-hr\" />\r\n</div>\r\n\r\n\r\n<script" +
                        " type=\"text/javascript\" src=\"/sites/fechado/Style%20Library/pt-br/Redecard/JScri" +
                        "pt/jquery-ui.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"/sites/fecha" +
                        "do/Angular/js/lib/angular.min.js\"></script>\r\n<script type=\"text/javascript\" src=" +
                        "\"/sites/fechado/Style Library/pt-br/Redecard/Jscript/jquery.selectBoxIt.min.js\">" +
                        "</script>\r\n<script type=\"text/javascript\" src=\"/sites/fechado/Style Library/pt-b" +
                        "r/Redecard/Jscript/jquery.ezmark.min.js\"></script>\r\n<script type=\"text/javascrip" +
                        "t\" src=\"/sites/fechado/Style%20Library/AtendimentoDigital/js/video.js\"></script>" +
                        "\r\n<script type=\"text/javascript\" src=\"/sites/fechado/Style%20Library/Atendimento" +
                        "Digital/js/video-service.js\"></script>\r\n<script type=\"text/javascript\" src=\"/sit" +
                        "es/fechado/Style%20Library/AtendimentoDigital/js/atendimento-module.js\"></script" +
                        ">\r\n<script type=\"text/javascript\" src=\"/sites/fechado/Style%20Library/Atendiment" +
                        "oDigital/js/atendimento-service.js\"></script>\r\n<script type=\"text/javascript\" sr" +
                        "c=\"/sites/fechado/Style Library/AtendimentoDigital/js/atendimento.js\"></script>\r" +
                        "\n\r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
