//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redecard.PN.RAV.Sharepoint.LAYOUTS {
    
    
    public partial class MA30 {
        
        /// <summary>
        /// txt_MA030_NUM_PDV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_NUM_PDV;
        
        /// <summary>
        /// txt_MA030_FUNCAO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_FUNCAO;
        
        /// <summary>
        /// txt_MA030_TIP_CREDITO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_TIP_CREDITO;
        
        /// <summary>
        /// txt_MA030_CANAL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CANAL;
        
        /// <summary>
        /// txt_MA030_VALOR_A_ANTECIPAR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_VALOR_A_ANTECIPAR;
        
        /// <summary>
        /// txt_MA030_CA_IND_ANTEC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CA_IND_ANTEC;
        
        /// <summary>
        /// txt_MA030_CA_VAL_ANTEC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CA_VAL_ANTEC;
        
        /// <summary>
        /// txt_MA030_CA_IND_DATA_ANTEC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CA_IND_DATA_ANTEC;
        
        /// <summary>
        /// txt_MA030_CA_PER_DATA_DE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CA_PER_DATA_DE;
        
        /// <summary>
        /// txt_MA030_CA_PER_DATA_ATE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CA_PER_DATA_ATE;
        
        /// <summary>
        /// txt_MA030_DAT_RESTRICAO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_DAT_RESTRICAO;
        
        /// <summary>
        /// txt_MA030_CA_IND_PRODUTO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CA_IND_PRODUTO;
        
        /// <summary>
        /// txt_MA030_DAT_PROCESSAMENTO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_DAT_PROCESSAMENTO;
        
        /// <summary>
        /// txt_MA030_HOR_PROCESSAMENTO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_HOR_PROCESSAMENTO;
        
        /// <summary>
        /// txt_MA030_BANCO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_BANCO;
        
        /// <summary>
        /// txt_MA030_CONTA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_CONTA;
        
        /// <summary>
        /// txt_MA030_AGENCIA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_AGENCIA;
        
        /// <summary>
        /// txt_MA030_VALOR_MINIMO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_VALOR_MINIMO;
        
        /// <summary>
        /// txt_MA030_HORA_INI_D0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_HORA_INI_D0;
        
        /// <summary>
        /// txt_MA030_HORA_FIM_D0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_HORA_FIM_D0;
        
        /// <summary>
        /// txt_MA030_HORA_INI_DN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_HORA_INI_DN;
        
        /// <summary>
        /// txt_MA030_HORA_FIM_DN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_HORA_FIM_DN;
        
        /// <summary>
        /// txt_MA030_PCT_DESCONTO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_PCT_DESCONTO;
        
        /// <summary>
        /// txt_MA030_VALOR_BRUTO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_VALOR_BRUTO;
        
        /// <summary>
        /// txt_MA030_VALOR_ORIG control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_VALOR_ORIG;
        
        /// <summary>
        /// txt_MA030_DAT_PERIODO_DE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_DAT_PERIODO_DE;
        
        /// <summary>
        /// txt_MA030_DAT_PERIODO_ATE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_DAT_PERIODO_ATE;
        
        /// <summary>
        /// txt_MA030_MSGERRO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_MSGERRO;
        
        /// <summary>
        /// txt_MA030_DATA_FIM_CARENCIA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_DATA_FIM_CARENCIA;
        
        /// <summary>
        /// txt_MA030_VALOR_ANTEC_D0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_VALOR_ANTEC_D0;
        
        /// <summary>
        /// txt_MA030_VALOR_ANTEC_D1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_VALOR_ANTEC_D1;
        
        /// <summary>
        /// txt_MA030_VALOR_DISP_ANTEC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_VALOR_DISP_ANTEC;
        
        /// <summary>
        /// txt_MA030_RV_QTD_RV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_MA030_RV_QTD_RV;
        
        /// <summary>
        /// btnExecutar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnExecutar;
        
        /// <summary>
        /// rptRetornoMA30 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptRetornoMA30;
        
        /// <summary>
        /// rptFiller control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptFiller;
        
        /// <summary>
        /// rptFiller1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptFiller1;
    }
}
